version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: custom
    directory: /snap
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    registries:
      - tailcat-upstream
    allow:
      - dependency-name: tailcat
    version-field: version

registries:
  tailcat-upstream:
    type: git
    tag-prefix: v
    url: https://github.com/tailscale/tailcat.git

