name: Tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Verify snap builds successfully
        id: build
        uses: canonical/action-build@v1

      - name: Determine system architecture
        run: echo "SYSTEM_ARCH=$(uname -m)" >> $GITHUB_ENV

      - name: Upload the built snap
        uses: actions/upload-artifact@v7
        with:
          name: snap_${{ env.SYSTEM_ARCH }}
          path: ${{ steps.build.outputs.snap }}

  func:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Determine system architecture
        run: echo "SYSTEM_ARCH=$(uname -m)" >> $GITHUB_ENV

      - name: Download snap file artifact
        uses: actions/download-artifact@v8
        with:
          name: snap_${{ env.SYSTEM_ARCH }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y snapd

      - name: Run func tests
        run: |
          sudo snap install --dangerous snap_${{ env.SYSTEM_ARCH }}
          bash tests/run_all.sh
