name: Tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Set up just
        uses: extractions/setup-just@v4

      - name: Run lint tests
        run: just lint

  build:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Snapcraft
        uses: canonical/craft-actions/snapcraft/setup@main

      - name: Verify snap builds successfully
        id: build
        uses: canonical/action-build@v1

      - name: Determine system architecture
        run: echo "SYSTEM_ARCH=$(uname -m)" >> $GITHUB_ENV

      - name: Upload the built snap
        uses: actions/upload-artifact@v7
        with:
          name: tailcat_snap_${{ env.SYSTEM_ARCH }}
          path: ${{ steps.build.outputs.snap }}

  test:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up LXD
        uses: canonical/setup-lxd@v1

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Set up just
        uses: extractions/setup-just@v4

      - name: Determine system architecture
        run: echo "SYSTEM_ARCH=$(uname -m)" >> $GITHUB_ENV

      - name: Download snap file artifact
        uses: actions/download-artifact@v8
        with:
          name: tailcat_snap_${{ env.SYSTEM_ARCH }}

      - name: Run func tests
        run: just test
